# version: '3.8'

# services:
#   ms-usuario:
#     build: .
#     container_name: ms-usuario
#     restart: always
#     ports:
#       - "5002:80"
#     networks:
#       - rede-compartilhada
#     entrypoint: ["/bin/sh", "-c", "until nc -z meu-postgres 5432; do echo Waiting for database; sleep 2; done; dotnet ms-usuario.dll"]

# networks:
#   rede-compartilhada:
#     external: true

version: '3.8'

services:
  ms-usuario:
    build: .
    container_name: ms-usuario
    ports:
      - "5000:5000"
    networks:
      - rede-compartilhada
    environment:
      - DB_HOST=ms-usuario-db
      - DB_NAME=usuario_db
      - DB_USER=usuario_user
      - DB_PASS=usuario_pass
    depends_on:
      - ms-usuario-db

  ms-usuario-db:
    image: postgres:latest
    container_name: ms-usuario-db
    environment:
      POSTGRES_USER: usuario_user
      POSTGRES_PASSWORD: usuario_pass
      POSTGRES_DB: usuario_db
    volumes:
      - ms-usuario-db-data:/var/lib/postgresql/data
    networks:
      - rede-compartilhada

networks:
  rede-compartilhada:
    external: true

volumes:
  ms-usuario-db-data:
