version: '3.8'

services:
  app:
    build: .
    ports:
      - "8102:5002" # Porta para acessar o aplicativo no host
      #- "8101:5001" # Porta HTTPS no host para o container
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DbContext=Host=ms-usuario-postgres-1;Port=5434;Pooling=true;Database=site-fisica;User Id=postgres;Password=admin
    networks:
      - default

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: site-fisica
    ports:
      - "5434:5434"
    networks:
      - default

networks:
  default:
    name: rede-compartilhada
    external: true