# version: '3.8'

# services:
#   ms-usuario:
#     build: .
#     container_name: ms-usuario
#     restart: always
#     ports:
#       - "5002:80"
#     networks:
#       - rede-compartilhada
#     entrypoint: ["/bin/sh", "-c", "until nc -z meu-postgres 5432; do echo Waiting for database; sleep 2; done; dotnet ms-usuario.dll"]

# networks:
#   rede-compartilhada:
#     external: true

version: '3.8'

services:
  app:
    build: .
    ports:
      - "8102:5002" # Porta para acessar o aplicativo no host
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DbContext=Host=postgres;Port=5432;Pooling=true;Database=site-fisica;User Id=postgres;Password=admin
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: site-fisica
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - ms-usuario-db-data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  ms-usuario-db-data: