version: '3.8'

services:
  app:
    build: .
    ports:
      - "8102:5002" # Porta para acessar o aplicativo no host
      #- "8101:5001" # Porta HTTPS no host para o container
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DbContext=Host=postgres;Port=5432;Pooling=true;Database=site-fisica;User Id=postgres;Password=admin
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: site-fisica
    ports:
      - "5434:5434"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge